#%RAML 1.0
title: Retail Notifications System API
version: v2.0
baseUri: http://localhost:8081/api

types: 
  Notification:
    type: object
    properties:
      id?: 
        type: string | integer
        description: Identifier of notification
      type:
        type: string
        enum: [SMS, EMAIL]
        description: Type of notification
      message?: 
        type: string | integer
        description: Information for recipient
      subject?: 
        type: string | integer
        description: Subject of message
      priority:
        type: string
        enum: [ URGENT, CRITICAL, MAJOR, MINOR, TRIVIAL]
        required: false
        description: Priority for notification
      recipient: 
        type: string | integer
        description: Recipient of notification


/notifications:
  description: |
    Working with notifications:
    * Creating notifications
  post:
    displayName: Create new notification
    description: |
      Create a new Notification
    body:
      application/json:
        type: Notification
        example: !include examples/notifications-request.yaml
    responses:
      200: